# Generated by Django 5.0.1 on 2024-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='suraiya', max_length=255),
        ),
    ]
